# Análise de dataset


A empresa Umbrella Corporation contratou desenvolvedores Python (🐍) para analisar um dataset para verificar o alto número de cancelamentos de contratos dessa empresa, e para entregar uma solução para este problema. 


Para isso, a Umbrella Corp. forneceu um *dataset* com os detalhes dos cancelamentos. Os Pythonianos(🐍) devem analisar o arquivo utilizando o **Panda** (🐼).


Vamos começar trazendo todos os dados de *dataset*:

vamos começar trazendo todos os dados do dataset:

In [1]:
import pandas as pd

tabela = pd.read_csv("cancelamentos.csv")
display(tabela)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
881661,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
881662,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
881663,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
881664,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
881665,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

## Tratamento de dados


Ao ler o *dataset*, percebemos que existem células com valore nulos, que atrapalham a nossa análise, e portanto devem ser retirados da análise.


Vamos Eliminá-los e re-exibir os valores, mas primeiro, precisaremos eliminar a coluna **ID** e re-exibir a tabela:

In [2]:
tabela = tabela.drop("CustomerID", axis=1)
display(tabela)

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
881661,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
881662,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
881663,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
881664,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
881665,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

Vamos pedir para que o Python nos retorne o número de linhas preenchidas da tabela.

In [3]:
display(tabela.info())

<class 'pandas.DataFrame'>
RangeIndex: 881666 entries, 0 to 881665
Data columns (total 11 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   idade                   881664 non-null  float64
 1   sexo                    881664 non-null  str
 2   tempo_como_cliente      881663 non-null  float64
 3   frequencia_uso          881663 non-null  float64
 4   ligacoes_callcenter     881664 non-null  float64
 5   dias_atraso             881664 non-null  float64
 6   assinatura              881661 non-null  str
 7   duracao_contrato        881663 non-null  str
 8   total_gasto             881664 non-null  float64
 9   meses_ultima_interacao  881664 non-null  float64
 10  cancelou                881664 non-null  float64
dtypes: float64(8), str(3)
memory usage: 74.0 MB

None

Veja que temoc em cada uma das colunas um número deiferente de linhas. Isso acontece porque temos dados nulos na tabela, e que devemod eliminar. Portanto , vamos elimná-los e através do comando Python abaixo e re-exibir a tabela

In [4]:
tebela = tabela.dropna()
display(tabela.info())

<class 'pandas.DataFrame'>
RangeIndex: 881666 entries, 0 to 881665
Data columns (total 11 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   idade                   881664 non-null  float64
 1   sexo                    881664 non-null  str
 2   tempo_como_cliente      881663 non-null  float64
 3   frequencia_uso          881663 non-null  float64
 4   ligacoes_callcenter     881664 non-null  float64
 5   dias_atraso             881664 non-null  float64
 6   assinatura              881661 non-null  str
 7   duracao_contrato        881663 non-null  str
 8   total_gasto             881664 non-null  float64
 9   meses_ultima_interacao  881664 non-null  float64
 10  cancelou                881664 non-null  float64
dtypes: float64(8), str(3)
memory usage: 74.0 MB

None

## Análise de dados


Ahora sim é que começa a análise de dados propriamente dita. Vamos começar verificando o número de clientes que cancelaram o contarto eo número de clientes que cancelaram.

In [5]:
display(tabela["cancelou"].value_counts())

cancelou
1.0    499998
0.0    381666
Name: count, dtype: int64

Podemos perceber que o número de clientes que cancelaram (1.0) realmente é alto, inclusive mais alto que o numero de clientes que não cancelaram, mas quanto que isso dá em procentagem? Vamos descobrir:

In [6]:
display(tabela["cancelou"].value_counts(normalize=True).map("{:.2%}".format))

cancelou
1.0    56.71%
0.0    43.29%
Name: proportion, dtype: str

Sabemos agora que aproximadamente % dos clientes cancelaram seus contratos. Nosso trabalho é descobrit o porquê.

In [7]:

display(tabela["duracao_contrato"].value_counts())
display(tabela["duracao_contrato"].value_counts(normalize=True).map("{:.2%}".format))

duracao_contrato
Annual       354396
Quarterly    353060
Monthly      174207
Name: count, dtype: int64

duracao_contrato
Annual       40.20%
Quarterly    40.04%
Monthly      19.76%
Name: proportion, dtype: str

Podemos perceber que existe uma minoria em relação aos contratos mensais, o que talvez possa significar que os cancelamentos estejam vindo dos contratos mensais.

O que acontece se retirarmos da análise os contratos mensais? Vamos ver se isso resolve o problema da empresa:

In [8]:
display(tabela["duracao_contrato"].value_counts())
display(tabela["duracao_contrato"].value_counts())


display(tabela.groupby("duracao_contrato").mean(numeric_only=True))

duracao_contrato
Annual       354396
Quarterly    353060
Monthly      174207
Name: count, dtype: int64

duracao_contrato
Annual       354396
Quarterly    353060
Monthly      174207
Name: count, dtype: int64

,idade,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,total_gasto,meses_ultima_interacao,cancelou
duracao_contrato,,,,,,,,
Annual,38.842188,31.446213,15.880213,3.263395,12.465135,651.696325,14.236120,0.460761
Monthly,41.552222,30.538632,15.499216,4.985661,15.007135,550.616445,15.478018,1.000000
Quarterly,38.830896,31.419838,15.886642,3.265247,12.460891,651.426516,14.234515,0.460256

Logo de cara percebemoc que todos os clientes que optaram pelo tipo de contrato mensal cancelaram o serviço

o que pode ser feito para resolver o problema dos contrartos mensais.


Podemos retirar o tipo de contrato mensal da análise para verificar qual porcentagem de cancelamentos que cobra:

In [9]:
tabel= tebela[tabela["duracao_contrato"] != "Momthly"]
display(tabela)
display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True).map("{:2%}".format))

C:\Users\ALUNO\AppData\Local\Temp\ipykernel_19332\2331533343.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tabel= tebela[tabela["duracao_contrato"] != "Momthly"]

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
881661,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
881662,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
881663,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
881664,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
881665,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

cancelou
1.0    499998
0.0    381666
Name: count, dtype: int64

cancelou
1.0    56.710720%
0.0    43.289280%
Name: proportion, dtype: str

Podemos verificar que sem o contrato do tipo mensal, a taxa de cancelamentos diminuiu para 46%. Só que a taxa de cancelamentos continua muito alta. Poratnto , precisaremos fazer uma análise ainda mais profunda nos contratos do tipo anual e trimestra.


Par termos uma noção melhor , vamos criar gráfico de cada coluna para verificar se há discrepâncias muito grandes nas taxas de cancelamentos em algumas dessas colunas:

In [ ]:
import plotly.express as px

for coluna in tabela.columns:
    grafico = px.histogram(tabela, x=coluna, color="cancelou", width=600)

    grafico.show()

Os gráficos indicam problemas com os usuários que fazem mais que 5 ligaçãoes para o call centaer, e também cancelamentos por parte dos usuários que passam mais de 20 dias inadiplentes. Portanto,devemos eliminar esses clientes da análise.

In [12]:
tabela = tabela[tabela["ligacoes_callcenter"] > 5]
tabela = tabela[tabela["dias_atraso"] <= 20]
display(tabela)
display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True).map("{:.2%}".format))

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
8,39.0,Male,12.0,5.0,7.0,4.0,Standard,Quarterly,969.00,13.0,1.0
16,19.0,Female,38.0,23.0,7.0,11.0,Basic,Quarterly,978.00,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
694515,64.0,Female,33.0,14.0,8.0,10.0,Premium,Annual,890.79,24.0,1.0
694519,50.0,Male,13.0,23.0,9.0,6.0,Basic,Quarterly,190.68,25.0,1.0
694523,24.0,Male,54.0,21.0,7.0,8.0,Premium,Monthly,102.56,2.0,1.0
694524,56.0,Male,42.0,30.0,9.0,7.0,Premium,Annual,337.81,20.0,1.0
694525,29.0,Female,46.0,9.0,8.0,19.0,Basic,Monthly,248.28,21.0,1.0

cancelou
1.0    160636
Name: count, dtype: int64

cancelou
1.0    100.00%
Name: proportion, dtype: str